name: Build, Test & Validate
on:
  push: 
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2
          problem-matchers: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup go
        uses:  actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run tests
        run: go test  -race -v  -covermode=atomic -coverprofile=cover.out ./...
      - name: Check Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml

